name: "build"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7, "3.0", 3.1, 3.2]
    continue-on-error: ${{ endsWith(matrix.ruby-version, 'head') }}
    env:
      RAILS_ENV: test
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby-version }} and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run tests
        run: bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal rake
      - name: Report code climate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
